version: "3.9"

networks:
  nginx-network:
    external: true
  media-management-network:
    external: true

services:

  sonarr:
    image: ghcr.io/linuxserver/sonarr:3.0.10
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${VOLUMES_PATH}/media-management/sonarr:/config
      - ${MEDIA_HDD_PATH}:/media
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - media-management-network

  radarr:
    image: ghcr.io/linuxserver/radarr:4.4.4
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${VOLUMES_PATH}/media-management/radarr:/config
      - ${MEDIA_HDD_PATH}:/media
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - media-management-network

  bazarr:
    image: ghcr.io/linuxserver/bazarr:1.2.1
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${VOLUMES_PATH}/media-management/bazarr:/config
      - ${MEDIA_HDD_PATH}/movies:/movies
      - ${MEDIA_HDD_PATH}/tv:/tv
      - ${MEDIA_HDD_PATH}/anime:/anime
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - media-management-network

  deluge:
    image: ghcr.io/linuxserver/deluge:2.1.1
    container_name: deluge
    # network_mode: host
    ports:
      - 8112:8112
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${VOLUMES_PATH}/media-management/deluge:/config
      - ${MEDIA_HDD_PATH}/downloads:/downloads
    restart: unless-stopped

  jellyfin:
    image: ghcr.io/linuxserver/jellyfin:arm32v7-10.8.10
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=${LOCAL_IP} #optional
    group_add: 
      - "44"
    volumes:
      - ${VOLUMES_PATH}/media-management/jellyfin:/config
      - ${MEDIA_HDD_PATH}/tv:/data/tvshows
      - ${MEDIA_HDD_PATH}/movies:/data/movies
      - ${MEDIA_HDD_PATH}/anime:/data/anime
      - ${MEDIA_HDD_PATH}/music:/data/music
      # - /home/pi/ssl:/ssl
      # - ${VOLUMES_PATH}/media-management/jellyfin-plugins:/jellyfin/jellyfin-web:ro
    # - /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
    # - 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri #optional
      - /dev/vcsm-cma:/dev/vcsm-cma #optional
      - /dev/vchiq:/dev/vchiq #optional
      - /dev/video10:/dev/video10 #optional
      - /dev/video11:/dev/video11 #optional
      - /dev/video12:/dev/video12 #optional
    restart: unless-stopped
    networks:
      - media-management-network
      - nginx-network

  nextcloud:
    image: ghcr.io/linuxserver/nextcloud:26.0.2
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      # - /home/pi/ssl:/config/keys
      - ${VOLUMES_PATH}/media-management/nextcloud:/config
      - ${BACKUP_HDD_PATH}/nextcloud:/data
    ports:
      - 1102:80
      - 1101:443
    restart: unless-stopped
    networks:
      - media-management-network
      - nginx-network
     
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:1.4.1
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${VOLUMES_PATH}/media-management/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - media-management-network
      
  tvheadend:
    image: ghcr.io/linuxserver/tvheadend:version-39df64bb
    container_name: tvheadend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - RUN_OPTS= #optional
    volumes:
      - ${VOLUMES_PATH}/media-management/tvheadend/data:/config
      - ${VOLUMES_PATH}/media-management/tvheadend/recordings:/recordings
    ports:
      - 9981:9981
      - 9982:9982
    devices:
      - /dev/dri:/dev/dri #optional
      - /dev/dvb:/dev/dvb #optional
    restart: unless-stopped
    networks:
      - media-management-network
     
  jellyseerr:
    image: fallenbagel/jellyseerr:1.5.0
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TIMEZONE}
    ports:
      - 5055:5055
    volumes:
      - ${VOLUMES_PATH}/media-management/jellyseerr/config:/app/config
    restart: unless-stopped
    networks:
      - media-management-network

