version: "2.1"
services:

  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - AUTO_UPDATE=true #optional
#      - RUN_OPTS=<run options here> #optional
    volumes:
      - /opt/appdata/jackett:/config
      - /mnt/hdd/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /home:/config/keys
      - /opt/appdata/nextcloud:/config
      - /mnt/hdd2:/data
    ports:
      - 1101:443
    restart: unless-stopped

  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - JELLYFIN_PublishedServerUrl=192.168.0.150 #optional
    volumes:
      - /opt/appdata/jellyfin:/config
      - /mnt/hdd/tv:/data/tvshows
      - /mnt/hdd/movies:/data/movies
      - /mnt/hdd/anime:/data/anime
      - /home:/ssl
      - /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
#      - 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri #optional
      - /dev/vcsm-cma:/dev/vcsm-cma #optional
      - /dev/vchiq:/dev/vchiq #optional
      - /dev/video10:/dev/video10 #optional
      - /dev/video11:/dev/video11 #optional
      - /dev/video12:/dev/video12 #optional
    restart: unless-stopped

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /opt/appdata/bazarr:/config
      - /mnt/hdd/movies:/movies
      - /mnt/hdd/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /opt/appdata/sonarr:/config
#      - /mnt/hdd/tv:/tv
#      - /mnt/hdd/downloads:/mnt/hdd/downloads
#      - /mnt/hdd/anime:/anime
      - /mnt/hdd:/media
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /opt/appdata/radarr:/config
#      - /mnt/hdd/movies:/movies
#      - /mnt/hdd/downloads:/mnt/hdd/downloads
      - /mnt/hdd:/media
    ports:
      - 7878:7878
    restart: unless-stopped

  homeassistant:
    image: ghcr.io/linuxserver/homeassistant
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /opt/appdata/homeassistant:/config
    restart: unless-stopped

  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /opt/appdata/deluge:/config
      - /mnt/hdd/downloads:/downloads
    restart: unless-stopped

  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /opt/appdata/nzbget:/config
      - /mnt/hdd/downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped
  
  grocy:
    image: ghcr.io/linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /opt/appdata/grocy:/config
    ports:
      - 9283:80
    restart: unless-stopped
