version: "3.9"

networks:
  nginx-network:
    external: true
  services:
    name: "services"
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1

services:

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - DOMAIN=https://${DOMAIN}/vault/
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_FROM=${SMTP_EMAIL}
      - SMTP_PORT=587
      - SMTP_SSL=true
      - SMTP_USERNAME=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
    volumes:
      - /opt/appdata/vaultwarden/data:/data
    networks:
      - nginx-network

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    volumes:
      - /opt/appdata/filebrowser/filebrowser.db:/database/filebrowser.db
      - /mnt:/srv
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    ports:
      - 8888:80
    restart: unless-stopped

  duplicati:
    image: duplicati/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - CLI_ARGS= #optional
    volumes:
      - /opt/appdata/duplicati2:/data
      - /mnt/hdd2/backups:/backups
      - /home/pi:/source
      - /opt/appdata:/docker-appdata
      - /mnt/hdd2/nextcloud/floryn08/files/InstantUpload/Camera:/mnt/hdd2/nextcloud/floryn08/files/InstantUpload/Camera
    ports:
      - 8200:8200
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /opt/appdata/readarr:/config
      - /mnt/hdd:/media #optional
    ports:
      - 8787:8787
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /opt/appdata/lidarr:/config
      - /mnt/hdd:/media #optional
    ports:
      - 8686:8686
    restart: unless-stopped

  cups: # user: print & pass: print
    container_name: cups
    image: unixorn/cupsd:latest
    ports:
      - 631:631
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev/bus/usb:/dev/bus/usb
      - /opt/appdata/cups/printers.conf:/etc/cups/printers.conf
    privileged: true
    restart: unless-stopped
    networks:
      - services

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/Bucharest'
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      PIHOLE_DNS_: 1.1.1.1
      ServerIP: ${LOCAL_IP}
    volumes:
      - /opt/appdata/pihole/etc-pihole/:/etc/pihole/
      - /opt/appdata/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 1.1.1.1
    networks:
      services:
        ipv4_address: 172.30.0.100 # static ip address  
    
  wireguard:
    dns: 172.30.0.100 # ip address of pihole from above
    environment:
      - WG_HOST=${DOMAIN}
      # Optional:
      # - PASSWORD=foobar123
      # - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=172.30.0.100 # ip address of pihole from above
      # - WG_ALLOWED_IPS=192.168.0.0/24, 0.0.0.0/0, ::/0
      
    image: weejewel/wg-easy
    container_name: wireguard
    volumes:
      - /opt/appdata/wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    depends_on:
      - pihole
    networks:
      - services

  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - AUTO_UPDATE=true #optional
#      - RUN_OPTS=<run options here> #optional
    volumes:
      - /opt/appdata/jackett:/config
      - /mnt/hdd/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - services

  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /home/pi/ssl:/config/keys
      - /opt/appdata/nextcloud:/config
      - /mnt/hdd2/nextcloud:/data
    ports:
      - 1102:80
      - 1101:443
    restart: unless-stopped
    networks:
      - services
      - nginx-network

  jellyfin:
    image: ghcr.io/linuxserver/jellyfin:10.8.4
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - JELLYFIN_PublishedServerUrl=${LOCAL_IP} #optional
    volumes:
      - /opt/appdata/jellyfin:/config
      - /mnt/hdd/tv:/data/tvshows
      - /mnt/hdd/movies:/data/movies
      - /mnt/hdd/anime:/data/anime
      - /mnt/hdd/music:/data/music
      - /home/pi/ssl:/ssl
      - /opt/appdata/jellyfin-plugins:/jellyfin/jellyfin-web:ro
#     - /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
#      - 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri #optional
      - /dev/vcsm-cma:/dev/vcsm-cma #optional
      - /dev/vchiq:/dev/vchiq #optional
      - /dev/video10:/dev/video10 #optional
      - /dev/video11:/dev/video11 #optional
      - /dev/video12:/dev/video12 #optional
    restart: unless-stopped
    networks:
      - services
      - nginx-network

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /opt/appdata/bazarr:/config
      - /mnt/hdd/movies:/movies
      - /mnt/hdd/tv:/tv
      - /mnt/hdd/anime:/anime
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - services

  sonarr:
    image: ghcr.io/linuxserver/sonarr:3.0.8.1507-ls143
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /opt/appdata/sonarr:/config
      - /mnt/hdd:/media
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - services

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /opt/appdata/radarr:/config
      - /mnt/hdd:/media
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - services

  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /opt/appdata/deluge:/config
      - /mnt/hdd/downloads:/downloads
    restart: unless-stopped

  grocy:
    image: ghcr.io/linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /opt/appdata/grocy:/config
    ports:
      - 9283:80
    restart: unless-stopped
    networks:
      - services
