version: "3.9"

networks:
  home-automation-network:
    external: true
  nginx-network:
    external: true
  mqtt-network:
    external: true

services:

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2023.3.1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    ports:
      - "8123:8123"
    volumes:
      - ${VOLUMES_PATH}/home-automation/homeassistant:/config
      # - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
#     networks:
#       - home-automation-network
#       - mqtt-network

  grocy:
    image: ghcr.io/linuxserver/grocy:3.3.2
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${VOLUMES_PATH}/home-automation/grocy:/config
    ports:
      - 9283:80
    restart: unless-stopped
    networks:
      - home-automation-network
      - nginx-network
      
      
  esphome:
    container_name: esphome
    image: esphome/esphome:2023.2
    volumes:
      - ${VOLUMES_PATH}/home-automation/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    #privileged: true
    network_mode: host
    ports:
      - 6052:6052
      - 6123:6123
#     networks:
#       - home-automation-network
