version: "3.9"

networks:
  home-automation-network:
    external: true
  cloudflare-network:
    external: true
  mqtt-network:
    external: true

services:

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2023.10.2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    ports:
      - "8123:8123"
    volumes:
      - ${VOLUMES_PATH}/home-automation/homeassistant:/config
    restart: unless-stopped
    privileged: true
    network_mode: host

  grocy:
    image: linuxserver/grocy:4.0.3
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${VOLUMES_PATH}/home-automation/grocy:/config
    ports:
      - 9283:80
    restart: unless-stopped
    networks:
      - home-automation-network
      - cloudflare-network
      
  esphome:
    container_name: esphome
    image: esphome/esphome:2023.9.3
    volumes:
      - ${VOLUMES_PATH}/home-automation/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
    ports:
      - 6052:6052
      - 6123:6123
