version: "3.9"

networks:
  home-automation-network:
    external: true
  cloudflare-network:
    external: true
  mqtt-network:
    external: true

services:

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2024.1.5
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    ports:
      - "8123:8123"
    volumes:
      - ${VOLUMES_PATH}/home-automation/homeassistant:/config
    restart: unless-stopped
    privileged: true
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123" ]
      interval: 10s
      timeout: 5s
      retries: 5

  grocy:
    image: linuxserver/grocy:4.0.3
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${VOLUMES_PATH}/home-automation/grocy:/config
    ports:
      - 9283:80
    restart: unless-stopped
    networks:
      - home-automation-network
      - cloudflare-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80" ]
      interval: 10s
      timeout: 5s
      retries: 5
      
  esphome:
    container_name: esphome
    image: esphome/esphome:2023.12.9
    volumes:
      - ${VOLUMES_PATH}/home-automation/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
    ports:
      - 6052:6052
      - 6123:6123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6052" ]
      interval: 10s
      timeout: 5s
      retries: 5
