version: "3.9"

networks:
  cloudflare-network:
    external: true
  db-network:
    external: true
  services:
    name: "services"
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1

services:

  pihole:
    container_name: pihole
    image: pihole/pihole:2024.01.0
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    environment:
      TZ: ${TIMEZONE}
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      PIHOLE_DNS_: 1.1.1.1
      ServerIP: ${LOCAL_IP}
    volumes:
      - ${VOLUMES_PATH}/utility-services/pihole/etc-pihole/:/etc/pihole/
      - ${VOLUMES_PATH}/utility-services/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 1.1.1.1
    networks:
      services:
        ipv4_address: 172.30.0.100 # static ip address  

  wireguard:
    dns: 172.30.0.100 # ip address of pihole from above
    environment:
      - WG_HOST=${DOMAIN}
      # Optional:
      # - PASSWORD=foobar123
      # - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=172.30.0.100 # ip address of pihole from above
      # - WG_ALLOWED_IPS=192.168.0.0/24, 0.0.0.0/0, ::/0

    image: ghcr.io/wg-easy/wg-easy:10
    container_name: wireguard
    volumes:
      - ${VOLUMES_PATH}/utility-services/wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    depends_on:
      - pihole
    networks:
      - services

  vaultwarden:
    image: vaultwarden/server:1.30.1
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - PUSH_ENABLED=true
      - PUSH_INSTALLATION_ID=${PUSH_INSTALLATION_ID}
      - PUSH_INSTALLATION_KEY=${PUSH_INSTALLATION_KEY}
      - SIGNUPS_ALLOWED=false
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_FROM=${SMTP_EMAIL}
      - SMTP_PORT=587
      - SMTP_SSL=true
      - SMTP_USERNAME=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
    volumes:
      - ${VOLUMES_PATH}/utility-services/vaultwarden/data:/data
    networks:
      - cloudflare-network

  cups:
    # user: print & pass: print
    container_name: cups
    image: unixorn/cupsd:latest
    ports:
      - 631:631
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      # - /var/run/dbus:/var/run/dbus
      # - /dev/bus/usb:/dev/bus/usb
      - ${VOLUMES_PATH}/utility-services/cups/printers.conf:/etc/cups/printers.conf
    privileged: true
    restart: unless-stopped
    
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:v0.7.2-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - 8083:8080
      - 8086:8086
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - /run/udev:/run/udev:ro
      - ${VOLUMES_PATH}/utility-services/scrutiny/config:/opt/scrutiny/config
    restart: unless-stopped
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail http://localhost:8080/api/health | grep -q 'true'
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 20s
      
  speedtest-tracker:
    image: ghcr.io/alexjustesen/speedtest-tracker:v0.14.4
    container_name: speedtest-tracker
    environment:
      PUID: 1000
      PGID: 1000
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: ${SPEEDTEST_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8081:80
      - 8443:443
    volumes:
      - ${VOLUMES_PATH}/utility-services/speedtest/config:/config
    networks:
      - db-network
    restart: unless-stopped
    
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.8.4
    container_name: homepage
    environment:
      - TZ=${TIMEZONE}
    ports:
      - 3000:3000
    volumes:
      - ${VOLUMES_PATH}/utility-services/homepage/config:/app/config
      - ${MEDIA_HDD_PATH}:/media
      - ${BACKUP_HDD_PATH}:/backup
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.4.0
    container_name: paperless-ngx
    environment:
      USERMAP_UID: 1000
      USERMAP_GID: 1000
      PAPERLESS_TIME_ZONE: ${TIMEZONE}
      PAPERLESS_REDIS: redis://redis
      PAPERLESS_OCR_LANGUAGES: ron #install romanian OCR
      PAPERLESS_OCR_LANGUAGE: ron #set default ocr language
    volumes:
      - ${MEDIA_HDD_PATH}/documents/paperless-ngx/data:/usr/src/paperless/data
      - ${MEDIA_HDD_PATH}/documents/paperless-ngx/media:/usr/src/paperless/media
      - ${MEDIA_HDD_PATH}/documents/paperless-ngx/export:/usr/src/paperless/export
      - ${MEDIA_HDD_PATH}/documents/paperless-ngx/consume:/usr/src/paperless/consume
    ports:
      - 8085:8000
    networks:
      - db-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
