version: '3.9'

services:
    ollama:
      container_name: ollama
      image: ollama/ollama:0.1.23
      volumes:
          - ${VOLUMES_PATH}/ai-services/ollama:/root/.ollama
      ports:
          - 11434:11434
      restart: unless-stopped

    ollama-webui:
      container_name: ollama-webui
      image: ghcr.io/ollama-webui/ollama-webui:main
      volumes:
        - ${VOLUMES_PATH}/ai-services/ollama-webui:/app/backend/data
      environment:
        - 'OLLAMA_API_BASE_URL=http://ollama:11434/api'
      ports:
        - 8088:8080
      depends_on:
        - ollama
      extra_hosts:
        - host.docker.internal:host-gateway
      restart: unless-stopped
    