version: '3.9'

networks:
  db-network:
    external: true
  nginx-network:
    external: true

services:

  ghost:
    image: ghost:alpine
    container_name: ghost
    restart: unless-stopped
    ports:
      - 8085:2368
    volumes:
      - ${VOLUMES_PATH}/website/ghost:/var/lib/ghost/content
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: mariadb #host from cinemacrawler docker compose
      database__connection__user: ${MYSQL_ROOT_USER}
      database__connection__password: ${MYSQL_ROOT_PASSWORD}
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: ${GHOST_URL}
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
    networks:
      - db-network
      - nginx-network
